### ISSUE TITLE
More stuff

### ISSUE THREAD

**Issue by RoySegall** [nirgn975/awesome-drupal#1]
Modules:
- [x] Features
- [x] Commerce
- [x] Views
- [x] Panels
- [x] Ctools
- [x] Search API
- [x] Entiy API
- [x] Entity cache
- [x] Date
- [x] Devel
- [x] Migrate
- [x] Entity validator
- [x] WYSIWYG

Distroutions
- [x] Commerce kickstart
- [x] OpenScholar

Scripts:
- [x] Apache solr script(mine)
- [x] Knowledge base ubuntu set up and mac

Blog posts:
- [x] How to install drush using composer
- [x] Use composer for set up Drupal 8

**Comment by nirgn975** [comment]
@RoySegall Can you paste here the link to the blog posts?
